name: Build and Push to ACR, Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Login to Azure using Service Principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3️⃣ Build and push Docker image to ACR
    - name: Build and Push image
      run: |
        az acr login --name mywebappacr01
        docker build -t mywebappacr01.azurecr.io/pythonapp:latest .
        docker push mywebappacr01.azurecr.io/pythonapp:latest

    # 4️⃣ Set AKS context
    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: webappk8cluster01      # replace with your AKS name
        resource-group: tilak-rg        # replace with your AKS resource group

    # 5️⃣ Deploy manifests to AKS
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
